// ------------
// structures
// ------------

#ifdef GLOBAL_NAMESPACE
auto ann_GLFWgamepadstate = make_smart<GLFWgamepadstate_GeneratedAnnotation>(lib);
addAnnotation(ann_GLFWgamepadstate);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_GLFWgammaramp = make_smart<GLFWgammaramp_GeneratedAnnotation>(lib);
addAnnotation(ann_GLFWgammaramp);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_GLFWvidmode = make_smart<GLFWvidmode_GeneratedAnnotation>(lib);
addAnnotation(ann_GLFWvidmode);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_GLFWimage = make_smart<GLFWimage_GeneratedAnnotation>(lib);
addAnnotation(ann_GLFWimage);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_GLFWgamepadstate,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_GLFWgammaramp,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_GLFWvidmode,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_GLFWimage,lib);
#endif

